pom.xml

This PR updates the version of `jackson` to fix CVE-2018-19360, CVE-2018-19362 and CVE-2018-19361.
This was found during a GitHub Security Scan.

Security alert: update version of jackson

---

bdd/pom.xml
engine/pom.xml
examples/pom.xml
pom.xml

This PR update the  `junit-jupiter` and `junit-vintage-engine` dependencies.
`junit-jupiter` meta package is used instead of `junit-jupiter-api`.

JUnit updates

---

.gitlab-ci.yml
examples/src/main/resources/application.yml

This PR uses our (@dbmdz) generic GitLab CI configuration.
Additionally, the CI configuration was extended to support Docker-in-Docker (*dind*) to run integration tests. 
For executing all integration tests, the `docker-compose` setup is booted and exports a rabbitmq server. 
Our *dind* setup does not allow us to communicate on `localhost` hostname, so `docker` must be set as hostname for accessing the rabbitmq server. Furthermore, a new spring boot profile (named `ci`) was introduced that also sets this specific hostname.

CI: Introduce GitLab CI setup

---

README.md
engine/src/main/java/de/digitalcollections/flusswerk/engine/flow/Flow.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/flow/FlowBuilder.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/jackson/FlowMessageMixin.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/model/FlowMessage.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/model/HasFlowId.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/model/Job.java
engine/src/test/java/de/digitalcollections/flusswerk/engine/flow/FlowBuilderTest.java
engine/src/test/java/de/digitalcollections/flusswerk/engine/jackson/FlowMessageMixinTest.java
engine/src/test/java/de/digitalcollections/flusswerk/engine/model/JobTest.java

For more complex setups it is useful to track the processing of one object between different workflow steps. Flusswerk uses the concept of FlowIds to do so. This PR adds automatic propagation from Incoming to Outgoing messages.

Propagate FlowIds

---

.gitlab-ci.yml

With this PR, uploading of artefacts to GitHub for a (pre-)release should work now.
The generic GitLab CI Configuration only caches all files located under `./target`. But `flusswerk` don't have a global `./target` folder. Instead, the `.jar` files are located under:
```bash
./bdd/target/dc-flusswerk-bdd-2.3.0-SNAPSHOT.jar
./engine/target/dc-flusswerk-engine-2.3.0.jar
./engine/target/dc-flusswerk-engine-2.3.0-javadoc.jar
./engine/target/dc-flusswerk-engine-2.3.0-sources.jar
./examples/target/dc-flusswerk-examples-2.3.0.jar
./examples/target/dc-flusswerk-examples-2.3.0-javadoc.jar
./examples/target/dc-flusswerk-examples-2.3.0-sources.jar
./integration/target/dc-flusswerk-integration-2.3.0.jar
```
This PR add these paths to the GitLab CI configuration. Uploading artefacts to GitHub should …

CI: Fix uploading of artefacts to GitHub

---

.gitlab-ci.yml

This PR adds OpenJDK 12 to the build matrix for integration tests.
---
**Note**: We are testing OpenJDK 12 internally. Whenever the CI image for OpenJDK 12 is rock-solid, the `only.variables==$USE_OPENJDK12` check can be removed.

CI: enable integration tests on OpenJDK 12

---

engine/src/main/java/de/digitalcollections/flusswerk/engine/messagebroker/RabbitConnection.java
engine/src/test/java/de/digitalcollections/flusswerk/engine/EngineTest.java

This is in accordance with the new WIP MDZ logging guidelines that stipulate that backing libraries should not log at the `INFO` level.

Change INFO logging outside of reporter to DEBUG

---

engine/src/main/java/de/digitalcollections/flusswerk/engine/reporting/ReportFunction.java
engine/src/test/java/de/digitalcollections/flusswerk/engine/EngineTest.java

This PR adds a new `ReportFunction` interface that allows defining a custom `ProcessReport` via an anonymous function:
```java
// Dummy reporter
ReportFunction nopReportFn = (type, msg, exc) -> {};
// Reporter that only logs failures
ReportFunction reportFn = (type, msg, exc) -> {
switch (type) {
case ReportType.FAIL:
case ReportType.FAIL_AFTER_MAX_RETRIES:
System.err.println("Message failed!");
default:
// NOP
}
}
```

Add functional interface for easy custom ProcessReports

---

.gitlab-ci.yml

Hi,
this PR introduces two minor changes in the CI configuration:
* To internally workaround this [Docker-in-Docker/GItLab](https://gitlab.com/charts/gitlab/issues/478) bug, we make the Docker-in-Docker image configurable. Internally, we use a *18.09.7-dind* tagged release of the `dind` image to mitigate failing builds (as mentioned in that issue)
* Setting `JAVA_HOME` is no longer needed, because this is already done in our CI `Dockerfile`

CI: Minor fixes

---

engine/src/main/java/de/digitalcollections/flusswerk/engine/messagebroker/RabbitConnection.java

When connection to RabbitMQ was not possible, the log messages were only at level debug,

Fix log level for connection errors

---

README.md
engine/src/main/java/de/digitalcollections/flusswerk/engine/model/DefaultMessage.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/model/FlusswerkMessage.java

All message implementations have to define and correctly initialize an
envelope field. This is not only prone to errors, but also dependent on
the internals of Flusswerk. An abstract base class encapsulates now the
technical specifics so that all implementations of the `Message` interface
now can focus on domain specific logic alone.

Add simpler way to implement custom message types

---

engine/src/main/java/de/digitalcollections/flusswerk/engine/messagebroker/RabbitConnection.java
spring-boot-starter-flusswerk/pom.xml
spring-boot-starter-flusswerk/src/main/java/de/digitalcollections/flusswerk/spring/boot/starter/FlusswerkConfiguration.java
spring-boot-starter-flusswerk/src/main/java/de/digitalcollections/flusswerk/spring/boot/starter/FlusswerkProperties.java
spring-boot-starter-flusswerk/src/main/java/de/digitalcollections/flusswerk/spring/boot/starter/FlusswerkPropertiesConfiguration.java
spring-boot-starter-flusswerk/src/test/java/de/digitalcollections/flusswerk/spring/boot/starter/FlusswerkPropertiesTest.java
spring-boot-starter-flusswerk/src/test/resources/application.yml

Flusswerk allows for a list of input queues, where the order defines the priority from which messages are read first. The Spring Boot Starter now provides the same configuration via `application.yml`.

Add priority queues to Spring Boot Starter

---

README.md
engine/src/main/java/de/digitalcollections/flusswerk/engine/jackson/DefaultMixin.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/messagebroker/MessageBrokerBuilder.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/messagebroker/RabbitConnection.java
engine/src/test/java/de/digitalcollections/flusswerk/engine/jackson/DefaultMixinTest.java
spring-boot-example/src/main/java/de/digitalcollections/flusswerk/spring/boot/example/config/FlusswerkConfig.java
spring-boot-starter-flusswerk/src/main/java/de/digitalcollections/flusswerk/spring/boot/starter/FlusswerkConfiguration.java
spring-boot-starter-flusswerk/src/main/java/de/digitalcollections/flusswerk/spring/boot/starter/MessageImplementation.java
spring-boot-starter-flusswerk/src/main/java/de/digitalcollections/flusswerk/spring/boot/starter/MessageMapping.java

In earlier versions any custom message implementation needed a Jackson mixin to configure serialization/deserialization. In most cases this is copy and paste of the same mixin. The new API does not require custom mixins anymore while keeping the possibility for fine grained control in case it is needed.

Add simplified and more flexible custom message types

---

spring-boot-starter-flusswerk/src/main/java/de/digitalcollections/flusswerk/spring/boot/starter/FlusswerkConfiguration.java
spring-boot-starter-flusswerk/src/main/java/de/digitalcollections/flusswerk/spring/boot/starter/FlusswerkProperties.java
spring-boot-starter-flusswerk/src/test/java/de/digitalcollections/flusswerk/spring/boot/starter/FlusswerkConfigurationTest.java

Almost all arguments are optional with sane defaults. The configuration
via application.yml should support the same behaviour and not produce
NullPointerExceptions.

Fix optional arguments in application.yml

---

engine/src/main/java/de/digitalcollections/flusswerk/engine/flow/FlowBuilder.java

For certain use cases (e.g. Spring configuration) a less verbose
FlowBuilder API is useful.

Add simpler FlowBuilder API

---

spring-boot-starter-flusswerk/src/main/java/de/digitalcollections/flusswerk/spring/boot/starter/FlusswerkConfiguration.java

The value for `virtualHost` can be `null` if the virtual host feature is not desired.

Fix NPE with Spring Boot starter

---

engine/src/main/java/de/digitalcollections/flusswerk/engine/flow/Flow.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/flow/FlowBuilder.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/flow/FlowStatus.java
engine/src/test/java/de/digitalcollections/flusswerk/engine/exceptions/ExceptionSupplierTest.java

To enable monitoring, each flow needs to provide execution information.
A callback can registered so that arbitrary monitoring code can be
integrated.

Add a simple metrics callback for monitoring

---

engine/pom.xml
examples-plain/pom.xml
examples-spring-boot/pom.xml
integration-tests/pom.xml
pom.xml
spring-boot-starter-flusswerk/pom.xml

Version 3.10 introduces
- Support for Spring Boot:
- a Spring Boot Starter for autoconfiguration
- configuration via application.yml
- provide metrics via Spring Boot actuator and Promtheus
- Improved exception handling:
- new exception types that are easier to understand
(StopProcessingException and RetryProcessingException)
- new exception types now require error descriptions in any case
- convenience API for error handling, esp. in combination with
Java's Optional
- Simplified custom messages:
- new base class for ready to go custom message implementations
- a new API to implement custom messages: Implementing
FlusswerMessage is now all you need
- Custom Jackson mixins are now optional
- new API for collecting metrics
- minor fixes and improvements
Version 3.1.0 prepares:
- The control …

Bump version to 3.1.0

---

engine/pom.xml
examples-plain/pom.xml
examples-spring-boot/pom.xml
integration-tests/pom.xml
pom.xml
spring-boot-starter-flusswerk/pom.xml
spring-boot-starter-flusswerk/src/main/java/de/digitalcollections/flusswerk/spring/boot/starter/FlusswerkProperties.java
spring-boot-starter-flusswerk/src/main/java/de/digitalcollections/flusswerk/spring/boot/starter/monitoring/MeterFactory.java
spring-boot-starter-flusswerk/src/test/java/de/digitalcollections/flusswerk/spring/boot/starter/monitoring/MeterFactoryTest.java

The existing had a bug in using the right prefix for metrics and app
name. This changeset fixes both.

Fix metrics configuration

---

engine/src/main/java/de/digitalcollections/flusswerk/engine/flow/FlowBuilder.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/flow/Type.java
engine/src/test/java/de/digitalcollections/flusswerk/engine/EngineTest.java
engine/src/test/java/de/digitalcollections/flusswerk/engine/ThreadBlockingTransformer.java

Java generics are limited as they are implemented using type erasure for
backwards compatibility. Therefore, specifying types using class
references does not work if the classes have generics. As this
information is used for typesafe builder pattern APIs, instances of a
generic Type-class can provide the missing information.

Add powerful type API for FlowBuilder

---

engine/src/main/java/de/digitalcollections/flusswerk/engine/flow/FlowBuilder.java
spring-boot-starter-flusswerk/src/main/java/de/digitalcollections/flusswerk/spring/boot/starter/FlusswerkConfiguration.java
spring-boot-starter-flusswerk/src/main/java/de/digitalcollections/flusswerk/spring/boot/starter/monitoring/Metrics.java

The new Metrics bean supports the common collection tasks for total
processed messages and total execution time, each counted seperately for
successful processing, processing with errors and retry, processing with
errors that lead to abort processing. This bean is only created if the
user does not provide a Metrics bean first.

Add metrics collection to Spring Boot starter

---

engine/src/main/java/de/digitalcollections/flusswerk/engine/flow/builder/ExperimentalFlowBuilder.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/flow/builder/Model.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/flow/builder/SetConfigurationStep.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/flow/builder/SetMessageProcessorStep.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/flow/builder/SetReaderStep.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/flow/builder/SetTransformerStep.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/flow/builder/SetWriterStep.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/model/TraceableMessage.java
engine/src/test/java/de/digitalcollections/flusswerk/engine/flow/builder/ExperimentalFlowBuilderTest.java
engine/src/test/java/de/digitalcollections/flusswerk/engine/flow/builder/InvocationProbe.java
engine/src/test/java/de/digitalcollections/flusswerk/engine/flow/builder/SetConfigurationStepTest.java
engine/src/test/java/de/digitalcollections/flusswerk/engine/flow/builder/SetMessageProcessorStepTest.java
engine/src/test/java/de/digitalcollections/flusswerk/engine/flow/builder/SetReaderStepTest.java
engine/src/test/java/de/digitalcollections/flusswerk/engine/flow/builder/SetTransformerStepTest.java
engine/src/test/java/de/digitalcollections/flusswerk/engine/flow/builder/SetWriterStepTest.java
engine/src/test/java/de/digitalcollections/flusswerk/engine/flow/builder/TestMessage.java

The new FlowBuilder API exposes only the necessary options for IDE
autocomplete and introduces a simplified process for message conversion
workflows.

Add prototype for new FlowBuilder API

---

framework/src/main/java/com/github/dbmdz/flusswerk/framework/flow/Flow.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/flow/builder/ConfigurationStep.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/flow/builder/Model.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/model/Job.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/flow/builder/ConfigurationStepTest.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/model/JobTest.java

In Flusswerk 3 tracing had to be explicitly enabled. Now the framework recognizes if a tracing id is present in the incoming messages and propagates to all new messages.
Closes #148.

Automatically propagate tracing ids if present

---

framework/src/main/java/com/github/dbmdz/flusswerk/framework/messagebroker/MessageBroker.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/messagebroker/RabbitClient.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/messagebroker/RabbitConnection.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/messagebroker/MessageBrokerTest.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/messagebroker/RabbitClientTest.java

The test API for working connections to RabbitMQ seems to been broken for a long time and therefore unused except for some unit tests that tested around the bug - removing for now completely.

Remove broken connection test

---

framework/src/main/java/com/github/dbmdz/flusswerk/framework/engine/Engine.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/flow/Flow.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/messagebroker/MessageBroker.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/model/Message.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/engine/EngineTest.java

When sending outgoing messages fails processing should stop as retrying
might cause situations that are very hard to debug (e.g. messages send
multiple times).
Fixes #149.

Fix error handling when sending messages fails

---

examples-spring-boot/pom.xml
framework/pom.xml
integration-tests/pom.xml
pom.xml

Flusswerk strongly builds upon Spring Boot. Therefore, dependency versions should be managed by Spring Boot where possible. Also, all other dependency versions are now only managed in the Maven parent pom.

Refactor dependency management

---

framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/properties/FlusswerkProperties.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/rabbitmq/MessageBroker.java

The Property name `rabbitMQ` shows up in autocomplete for `application.yml` as `rabbit-m-q`, so it is renamed to `rabbitmq`.

Rename property for better IDE autocomplete

---

.gitlab-ci.yml

The caching paths for GitLab CI did not match the current project structure.

Fix CI caching paths

---

README.md
README_3.2.md
framework/src/main/java/com/github/dbmdz/flusswerk/framework/flow/builder/MessageProcessorStep.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/flow/builder/MessageProcessorStepTest.java

Sometimes a workflow job should only consume incoming messages, but does
not want the Flusswerk framework to handle any messages to send.

Add consuming message processor

---

pom.xml

Adds the versions of the Maven plugins for formatting and Git commit
hooks to plugin management and adds auto-formatting before commit for
the Flusswerk codebase.

Configure formatting as default

---

examples-spring-boot/src/main/java/com/github/dbmdz/flusswerk/spring/boot/example/config/FlusswerkConfig.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/FlusswerkConfiguration.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/properties/StringRepresentation.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/engine/Engine.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/flow/Flow.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/flow/FlowSpec.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/flow/builder/ConfigurationStep.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/model/IncomingMessageType.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/engine/EngineTest.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/exceptions/ExceptionSupplierTest.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/fixtures/Flows.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/flow/builder/FlowBuilderTest.java
integration-tests/src/test/java/com/github/dbmdz/flusswerk/integration/RetryTest.java
integration-tests/src/test/java/com/github/dbmdz/flusswerk/integration/SuccessfulProcessingTest.java

After `FlowSpec` is created, both `FlowSpec` and `Flow` are only used internally. The typechecking for the use in Flusswerk apps is completely handled in the FlowBuilder. Therefore, removing generics from APIs makes it much easier to use Flusswerk.

Simplify api

---

framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/properties/RabbitMQProperties.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/config/properties/RabbitMQPropertiesTest.java

If the hosts entry in `application.yml` are missing, `localhost` should be used.

Fix default hosts

---

framework/src/main/java/com/github/dbmdz/flusswerk/framework/engine/Engine.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/engine/EngineTest.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/fixtures/Flows.java

If the Writer is a Consumer, then there are no messages to send, and the application does not need to declare a default outgoing topic. The Framework should not attempt to start sending messages in that case and then fail if there is no default.

Fix attempt to send messages when the Writer did not create one

---

framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/FlusswerkConfiguration.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/FlusswerkPropertiesConfiguration.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/properties/AppProperties.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/properties/RoutingProperties.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/monitoring/MeterFactory.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/config/properties/AppPropertiesTest.java
framework/src/test/resources/application.yml

The Spring Boot application name is used for monitoring and logging, but implementation had bugs. This MR now introduces a proper ConfigurationProperties class for `spring.application.name`.

Introduce proper properties for app name

---

framework/src/main/java/com/github/dbmdz/flusswerk/framework/model/Message.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/model/MessageTest.java

Both `equals() `and _hashCode()_ have to consider the same fields. Since the purpose of `Envelope` is to contain the information the framework needs to manage the processing, it should not be included.

Fix wrong Message.hashCode

---

.github/workflows/ci.yml
.gitlab-ci.yml
framework/pom.xml
integration-tests/pom.xml
pom.xml

Flusswerk 4 recommends to use the Flusswerk 4 parent pom for workflow jobs. This caused the Nexus Staging Maven Plugin to be part of any workflow job, interfering with existing deployment strategies.
To solve this, a new maven profile `maven-central` was introduced (replacing the `deploy` profile) to explicitely use the Nexus Staging Plugin in the deployment build.

Snapshot-Deployments

---

.github/workflows/ci.yml
.github/workflows/snapshots.yml

Builds with the same pom can safely cache `.m2/repository` to speed up builds.

Cache maven dependencies

---

.github/workflows/snapshots.yml

The new caching action was missing indents, therefore leading to an invalid configuration.

Fix GitHub Actions YAML for Snapshots

---

pom.xml

Maven parent projects cannot configure default deployment, as this would set the deployment for every child project as well. A separate Maven profile for deployment for maven central sets the target, and another profile can be invoked to activate signing.
Deployment of a Snapshot:
```
mvn deploy -P maven-central
```
Deployment of a Release:
```
mvn deploy -P maven-central,sign
```

Fix Snapshot deployments

---

framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/FlusswerkConfiguration.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/jackson/FlusswerkObjectMapper.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/rabbitmq/RabbitClient.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/jackson/DefaultMixinTest.java

We introduce a FlusswerkObjectMapper that builds upon a Jackson
ObjectMapper but includes all Flusswerk specific configurations and a
method to deserialize JSON to Message directly. This does not only
simplify the architecture, but should makes testing more flexible and
powerful.

Refactor JSON handling to FlusswerkObjectMapper

---

framework/src/main/java/com/github/dbmdz/flusswerk/framework/flow/Flow.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/flow/FlowInfo.java

For some cases (like different data sources) it can be useful to use information from the message to calculate or label metrics. This MR makes the processed Message instance available where metrics are calculated.

Enable message-specific metrics

---

framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/FlusswerkConfiguration.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/monitoring/BaseMetrics.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/monitoring/DefaultFlowMetrics.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/monitoring/BaseMetricsTest.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/monitoring/DefaultFlowMetricsTest.java

With this PR you can simply replace the DefaultFlowMetrics so that you can e.g. add specific tags to item count or time used.

Make FlowMetrics more flexible

---

framework/pom.xml
framework/src/main/java/com/github/dbmdz/flusswerk/framework/model/Envelope.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/reporting/StructuredProcessReport.java
integration-tests/pom.xml
pom.xml

Logging had a timestamp field that was derived from when the message was first created. This is more confusing than useful and will therefore be removed.

Remove extra timestamp

---

framework/src/main/java/com/github/dbmdz/flusswerk/framework/reporting/FlusswerkLogger.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/reporting/FlusswerkLoggerTest.java

Throwables must be the last in a list of arguments. This MR ensures that the behaviour of `FlusswerkLogger.error(String, Object...)` (and the other log levels) is equal to the corresponding methods of SLF4J and Logback.

Fix order of logger arguments

---

framework/pom.xml
framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/FlusswerkConfiguration.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/rabbitmq/RabbitConnection.java
integration-tests/pom.xml
pom.xml

The application name is displayed next to the connection in the RabbitMQ management view. The application name is only extra information for ops, not an unique identifier - multiple instances can report the same name.

 Add application name to RabbitMQ connection

---

framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/properties/AppProperties.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/properties/FlusswerkProperties.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/properties/MonitoringProperties.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/properties/ProcessingProperties.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/properties/RabbitMQProperties.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/properties/RedisProperties.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/properties/RoutingProperties.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/properties/StringRepresentation.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/config/properties/FlusswerkPropertiesTest.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/config/properties/StringRepresentationTest.java

This changes the String representation of all Flusswerk configuration property beans to YAML to remove a lot of complicated logic.
This does not introduce new dependencies because SnakeYAML is already a dependency of Spring Boot.

Refactor properties string representation

---

framework/src/main/java/com/github/dbmdz/flusswerk/framework/engine/Worker.java

The processing time for one item can be interesting for performance optimizations.

Add duration in seconds to logging

---

framework/src/main/java/com/github/dbmdz/flusswerk/framework/flow/Flow.java

The log values for `duration` and `duration_ms` where switched. Number format is changed to avoid exponential notation, so log parsers do not have to support this.

Fix duration logging

---

framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/FlusswerkConfiguration.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/engine/FlusswerkConsumer.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/engine/Task.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/engine/Worker.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/engine/FlusswerkConsumerTest.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/engine/WorkerTest.java

There should be only one class responsible for managing the consumer semaphore.
There are two possible scenarios when the processing is done and the semaphore should be freed:
- on the consumer end: when the processing is done (successful or with error)
- on the producer end: when there was an error that prevents processing from even starting (deserializing message fails)
To ensure single responsibility and minimize the risk of double-freeing or not-freeing the semaphore at all, the class responsible for acquiring the semaphore should also be responsible for freeing (FlusswerkConsumer). The other case (Worker) will be handled with a callback set by FlusswerkConsumer.

Refactor consumer semphore handling for single responsibility

---

framework/pom.xml
framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/FlusswerkConfiguration.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/monitoring/MeterFactory.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/monitoring/MeterFactoryTest.java
integration-tests/pom.xml
pom.xml

The `job` label in Prometheus should be handled by the static Prometheus configuration or the Prometheus service discovery.

Fix prometheus labels

---

framework/src/main/java/com/github/dbmdz/flusswerk/framework/flow/Flow.java

Tracing-IDs got lost when a SkipProcessingException was thrown. This PR moves propagation of tracing IDs to the correct place.

Fix missing tracing information for exceptions

---

framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/FlusswerkConfiguration.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/engine/Worker.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/monitoring/DefaultFlowMetrics.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/monitoring/FlusswerkMetrics.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/monitoring/MeterFactory.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/engine/WorkerTest.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/monitoring/DefaultFlowMetricsTest.java

So far, Flusswerk defines two metrics out-of-the-box: total amount processed messages, and total time spent processing the message.
There are two issues with the current implementation:
1. the names are not following Prometheus best practices
2. framework metrics and user defined metrics share the same prefix as configured with `flusswerk.monitoring.basename` (default: "flusswerk")
This PR introduces two new metrics that are named independently from the value of basename and that follow best practices:
`flusswerk_messages_total` is the total number of messages processed since start of the application, `flusswerk_processing_seconds` the time spent on processing. Values from parallel threads are added up.

Introduce proper framework metrics

---

CHANGES.md
framework/pom.xml
integration-tests/pom.xml
pom.xml

- Message processing can now be skipped by throwing a SkipProcessingException. Log messages now have a field `status` to indicate this. ([#355](https://github.com/dbmdz/flusswerk/pull/355))
- New framework metrics `flusswerk_messages_total` and `flusswerk_messages_seconds` (Counter). The prefix is independent from the application prefix since the metric is the same for all Flusswerk-based applications. ([#381](https://github.com/dbmdz/flusswerk/pull/381)).
- New framework metrics `flusswerk_workers` (Gauge). The prefix is independent from the application prefix since the metric is the same for all Flusswerk-based applications. ([#381](https://github.com/dbmdz/flusswerk/pull/381)).
- Flusswerk applications now can send raw messages: `Topic.sendRaw(byte[] message)` …

Bump version to 5.1.0

---

.github/workflows/ci.yml
framework/pom.xml
framework/src/main/java/com/github/dbmdz/flusswerk/framework/rabbitmq/MessageBroker.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/rabbitmq/Queue.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/rabbitmq/RabbitClient.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/rabbitmq/RabbitConnection.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/rabbitmq/MessageBrokerTest.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/rabbitmq/QueueTest.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/rabbitmq/RabbitClientTest.java
integration-tests/pom.xml
integration-tests/src/test/java/com/github/dbmdz/flusswerk/integration/NoFlowTest.java
integration-tests/src/test/java/com/github/dbmdz/flusswerk/integration/RabbitUtil.java
integration-tests/src/test/java/com/github/dbmdz/flusswerk/integration/processing/ReconnectTest.java
integration-tests/src/test/java/com/github/dbmdz/flusswerk/integration/processing/RetryTest.java
integration-tests/src/test/java/com/github/dbmdz/flusswerk/integration/processing/SkipProcessingTest.java
integration-tests/src/test/java/com/github/dbmdz/flusswerk/integration/processing/SuccessfulProcessingTest.java
pom.xml

Previously Flusswerk implemented a custom connection recovery mechanism that had a fair amount of problems, most importantly a deadlocked application in case of connection loss with outstanding messages.
This change modifies Flusswerk to use the recovery mechanism baked into the RabbitMQ Java client library, which in addition to making the connection recovery work reliably, simplifies the API for users, since most methods on `RabbitClient` no longer throw an `IOException`.

Rely on automatic connection recovery instead of manually managing it.

---

CHANGES.md
framework/pom.xml
integration-tests/pom.xml
pom.xml

- Rely on automatic connection recovery instead of managing it manually ([#410](https://github.com/dbmdz/flusswerk/pull/410/commits))
- Flusswerk metrics separated from application metrics ([#405](https://github.com/dbmdz/flusswerk/pull/405))
- Tracing information added to messages send with `SkipProcessingException` ([#404](https://github.com/dbmdz/flusswerk/pull/404))

Bump version to 5.1.1

---

CHANGES.md
README.md
framework/src/main/java/com/github/dbmdz/flusswerk/framework/flow/FlowInfo.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/monitoring/FlusswerkMetrics.java

This PR fixes the time unit for `flusswerk.messages.seconds`.

Record processing time in seconds

---

CHANGES.md
framework/pom.xml
integration-tests/pom.xml
pom.xml

- The Counter `flusswerk_messages_seconds` now records the processing time in seconds ([#444](https://github.com/dbmdz/flusswerk/pull/444))
- Flusswerk default metrics names now follow best practices ([#420](https://github.com/dbmdz/flusswerk/pull/420))
- The DefaultProcessReport now supports common defaults and sensible structured fields so that most applications don't need to implement their own ProcessReport anymore ([DefaultProcessReport](https://github.com/dbmdz/flusswerk/blob/main/framework/src/main/java/com/github/dbmdz/flusswerk/framework/reporting/DefaultProcessReport.java))
- Migrated to SpringBoot 3 / JDK17
- `flowInfo.duration()` returns a `Duration` object instead of `long` ([#444](https://github.com/dbmdz/flusswerk/pull/444))
- Support for partial retries: When a workload is …

Release 6.0.0

---

.github/workflows/ci.yml

Hi,
this PR introduces Ubuntu 24.04 as new image version for both builds and releases.

CI: Update version of Ubuntu image

---

framework/src/main/java/dev/mdz/flusswerk/FlusswerkApplication.java
framework/src/main/java/dev/mdz/flusswerk/LifecyclePhases.java
framework/src/main/java/dev/mdz/flusswerk/engine/Engine.java
framework/src/main/java/dev/mdz/flusswerk/rabbitmq/RabbitClient.java
framework/src/main/java/dev/mdz/flusswerk/rabbitmq/RabbitConnection.java

This is a first draft to use Spring's life cycle management to gracefully stop the connection to RabbitMQ and simplify the setup of clicent applications.
In further versions, this could be used to build a more resilient connection handling in case of server reboots or RabbitMQ restarts.

Add lifecycle management to tear down connections
