pom.xml

This PR fixes CVE-2018-11087 and updates the version of amqp-client.

GitHub security alert: update version of amqp-client

---

engine/src/main/java/de/digitalcollections/flusswerk/engine/messagebroker/RabbitClient.java

When RabbitMQ was restarted after Flusswerk has established a connection, the application would freeze and end up in an unrecoverable state. This PR introduces a very resilient connection handling.

Fix reconnecting behavior when RabbitMQ is restarted

---

pom.xml
spring-boot-example/pom.xml
spring-boot-example/src/main/java/de/digitalcollections/flusswerk/spring/boot/example/Application.java
spring-boot-example/src/main/java/de/digitalcollections/flusswerk/spring/boot/example/ComposePerfectGreeting.java
spring-boot-example/src/main/java/de/digitalcollections/flusswerk/spring/boot/example/FancyConsoleProcessReport.java
spring-boot-example/src/main/java/de/digitalcollections/flusswerk/spring/boot/example/config/FlusswerkConfig.java
spring-boot-example/src/main/java/de/digitalcollections/flusswerk/spring/boot/example/model/Greeting.java
spring-boot-example/src/main/java/de/digitalcollections/flusswerk/spring/boot/example/model/GreetingMixin.java
spring-boot-example/src/main/resources/application.yml
spring-boot-starter-flusswerk/pom.xml
spring-boot-starter-flusswerk/src/main/java/de/digitalcollections/flusswerk/spring/boot/starter/EnableFlusswerk.java
spring-boot-starter-flusswerk/src/main/java/de/digitalcollections/flusswerk/spring/boot/starter/FlusswerkConfiguration.java
spring-boot-starter-flusswerk/src/main/java/de/digitalcollections/flusswerk/spring/boot/starter/FlusswerkProperties.java
spring-boot-starter-flusswerk/src/main/java/de/digitalcollections/flusswerk/spring/boot/starter/MessageMapping.java
spring-boot-starter-flusswerk/src/main/java/de/digitalcollections/flusswerk/spring/boot/starter/StringRepresentation.java
spring-boot-starter-flusswerk/src/test/java/de/digitalcollections/flusswerk/spring/boot/starter/StringRepresentationTest.java

Adds a Spring Boot starter module to
- Load configuration from `application.yml`
- Enable autowiring for all Job-specific components
...to make new Spring-based workflow jobs easy as pie  🤖 👩‍🔧 👨‍🔧 ✨ ✨ ✨

Add Spring Boot Starter draft

---

spring-boot-starter-flusswerk/src/main/java/de/digitalcollections/flusswerk/spring/boot/starter/StringRepresentation.java
spring-boot-starter-flusswerk/src/test/java/de/digitalcollections/flusswerk/spring/boot/starter/StringRepresentationTest.java

Format code

---

spring-boot-starter-flusswerk/src/main/java/de/digitalcollections/flusswerk/spring/boot/starter/FlusswerkConfiguration.java

When using application.yml as property source with optional parameters,
then there almost everything can be null. Thourough null checking now
prevents unwanted exceptions.

Fix NPE in properties from application.yml

---

engine/pom.xml
engine/src/main/java/de/digitalcollections/flusswerk/engine/Engine.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/exceptions/ExceptionSupplier.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/exceptions/FinallyFailedProcessException.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/exceptions/RetriableProcessException.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/exceptions/RetryProcessingException.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/exceptions/StopProcessingException.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/reporting/CompactProcessReport.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/reporting/DefaultProcessReport.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/reporting/ProcessReport.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/reporting/ReportFunction.java
pom.xml
spring-boot-example/src/main/java/de/digitalcollections/flusswerk/spring/boot/example/FancyConsoleProcessReport.java
spring-boot-starter-flusswerk/src/main/java/de/digitalcollections/flusswerk/spring/boot/starter/FlusswerkApplication.java
spring-boot-starter-flusswerk/src/main/java/de/digitalcollections/flusswerk/spring/boot/starter/FlusswerkConfiguration.java
spring-boot-starter-flusswerk/src/test/java/de/digitalcollections/flusswerk/spring/boot/starter/FlusswerkConfigurationTest.java

This changeset includes
- easier to use exception classes, including fluent suppliers
- an easier to use CompactProcessReport for structured logging
- a Spring Boot application base class to reduce boilerplate code for
most applications

Refactor for API improvements

---

engine/src/main/java/de/digitalcollections/flusswerk/engine/exceptions/ExceptionSupplier.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/exceptions/RetryProcessingException.java
engine/src/main/java/de/digitalcollections/flusswerk/engine/exceptions/StopProcessingException.java
engine/src/test/java/de/digitalcollections/flusswerk/engine/exceptions/ExceptionSupplierTest.java

Add missing constructors and access permissions for private constructors.

Fix exception supplier

---

examples-spring-boot/pom.xml
examples-spring-boot/src/main/java/de/digitalcollections/flusswerk/spring/boot/example/Metrics.java
examples-spring-boot/src/main/java/de/digitalcollections/flusswerk/spring/boot/example/config/FlusswerkConfig.java
examples-spring-boot/src/main/resources/application.yml
spring-boot-starter-flusswerk/src/main/java/de/digitalcollections/flusswerk/spring/boot/starter/FlusswerkProperties.java
spring-boot-starter-flusswerk/src/main/java/de/digitalcollections/flusswerk/spring/boot/starter/monitoring/MeterFactory.java

Convenience factory to make the creation of a monitoring bean easier.

Meter factory

---

spring-boot-starter-flusswerk/src/main/java/de/digitalcollections/flusswerk/spring/boot/starter/monitoring/MeterFactory.java

Docstring for constructor of `MeterFactory` was incomplete.

Add missing docstring

---

engine/pom.xml
examples-plain/pom.xml
examples-spring-boot/pom.xml
integration-tests/pom.xml
pom.xml
spring-boot-starter-flusswerk/pom.xml

Version 3.1.1 fixes issues with the Spring Boot configuration.

Bump version to 3.1.1

---

.gitignore
engine/pom.xml
engine/src/main/java/de/digitalcollections/flusswerk/engine/EngineStats.java
engine/src/test/java/de/digitalcollections/flusswerk/engine/EngineTest.java
engine/src/test/java/de/digitalcollections/flusswerk/engine/ThreadBlockingTransformer.java
examples-plain/pom.xml
examples-spring-boot/pom.xml
integration-tests/pom.xml
pom.xml
spring-boot-starter-flusswerk/pom.xml

Existing tests for the Flusswerk Engine were complicated and fragile. This refactoring simplifies the testsetup and should add more stability to the tests.

Improve Tests

---

framework/src/main/java/com/github/dbmdz/flusswerk/framework/flow/Flow.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/flow/FlowBuilder.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/messagebroker/FailurePolicy.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/messagebroker/MessageBrokerBuilderTest.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/messagebroker/MessageBrokerTest.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/messagebroker/RabbitClientTest.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/model/JobTest.java
integration-tests/src/test/java/com/github/dbmdz/flusswerk/integration/Backend.java

Cleanups, mostly as suggested by the IDE. This should fix the merge/rebase conflicts.

Cleanup code

---

framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/FlusswerkConfiguration.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/engine/Engine.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/engine/EngineTest.java

Simplify API surface and improve separation of concerns.

Refactor engine construction

---

framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/properties/RabbitMQProperties.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/properties/StringRepresentation.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/rabbitmq/RabbitConnection.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/config/properties/FlusswerkPropertiesTest.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/config/properties/StringRepresentationTest.java
framework/src/test/resources/application.yml
integration-tests/src/test/resources/application.yml

Reenables the configuration of more than one RabbitMQ host.

Fix host config

---

framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/FlusswerkConfiguration.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/FlusswerkPropertiesConfiguration.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/properties/MonitoringProperties.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/properties/ProcessingProperties.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/properties/RabbitMQProperties.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/properties/RedisProperties.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/properties/RoutingProperties.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/monitoring/MeterFactory.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/config/properties/RedisPropertiesTest.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/monitoring/MeterFactoryTest.java
integration-tests/src/test/java/com/github/dbmdz/flusswerk/integration/RetryTest.java
integration-tests/src/test/java/com/github/dbmdz/flusswerk/integration/SuccessfulProcessingTest.java

Make each properties class available as bean.

Refactor code to modularize properties

---

README.md
docker-compose.yml
framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/FlusswerkConfiguration.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/properties/RedisProperties.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/exceptions/LockingException.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/locking/LockContext.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/locking/LockManager.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/locking/NoOpLockManager.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/locking/RedisLockManager.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/locking/SystemWatch.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/locking/Watch.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/config/properties/RedisPropertiesTest.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/locking/LockContextTest.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/locking/LockingFixture.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/locking/NoOpLockManagerTest.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/locking/RedisLockManagerTest.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/locking/SystemWatchTest.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/locking/TestingWatch.java
integration-tests/src/test/java/com/github/dbmdz/flusswerk/integration/LockingTest.java
integration-tests/src/test/java/com/github/dbmdz/flusswerk/integration/ProcessorAdapter.java
integration-tests/src/test/java/com/github/dbmdz/flusswerk/integration/RabbitUtil.java
integration-tests/src/test/java/com/github/dbmdz/flusswerk/integration/RedisUtil.java
integration-tests/src/test/java/com/github/dbmdz/flusswerk/integration/locking/LockingTest.java
integration-tests/src/test/java/com/github/dbmdz/flusswerk/integration/locking/LocksAreEffectiveTest.java
integration-tests/src/test/java/com/github/dbmdz/flusswerk/integration/processing/RetryTest.java
integration-tests/src/test/java/com/github/dbmdz/flusswerk/integration/processing/SuccessfulProcessingTest.java
integration-tests/src/test/resources/application.yml

Add centralized locking via Redis.

Redis Locking

---

README.md
framework/pom.xml
integration-tests/pom.xml
pom.xml

Prepare release of version 4.0.0.

Release version 4.0.0

---

.github/workflows/ci.yml
.github/workflows/snapshots.yml
integration-tests/src/test/resources/application.yml

Experimental CI setup to test GitHub Actions as a possible CI alternative.

Add Github actions as a simple experimental CI alternative

---

framework/pom.xml
integration-tests/pom.xml
pom.xml

Release 4.01. fixes a bug in Maven dependency management.

Release v4.0.1

---

framework/src/main/java/com/github/dbmdz/flusswerk/framework/rabbitmq/Queue.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/rabbitmq/RabbitMQ.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/rabbitmq/Topic.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/engine/NoOpEngineTest.java

Adds more API docs and a Unit Test for NoOpEngine.

Docs and tests

---

framework/src/main/java/com/github/dbmdz/flusswerk/framework/reporting/DefaultProcessReport.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/reporting/StructuredProcessReport.java

This PR allows inherited DefaultProcessReports to overwrite the Logger

Let inherited ProcessReports overwrite the logger

---

README.md
framework/pom.xml
integration-tests/pom.xml
pom.xml

Prepares release of Flusswerk 4.1.0. This release includes:
- largely improved structured logging with `StructuredProcessReport`
- tracing paths to trace message propagation throughout a complex workflow setup
- Flows are now optional to support Flusswerk as pure message sender
- Metrics allow now for a more flexible custom implementation

Bump version to 4.1.0

---

framework/pom.xml
framework/src/main/java/com/github/dbmdz/flusswerk/framework/reporting/StructuredProcessReport.java
integration-tests/pom.xml
pom.xml

The fields used were conflicting with other common used field names.

Fix logging fields

---

framework/pom.xml
integration-tests/pom.xml
pom.xml

Release 4.1.2 resolves an ambiguous timestamps in logging output.

Release 4.1.2

---

framework/pom.xml
framework/src/main/java/com/github/dbmdz/flusswerk/framework/reporting/FlusswerkLogger.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/reporting/FlusswerkLoggerFactory.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/reporting/FlusswerkProcessReport.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/reporting/FlusswerkLoggerTest.java
integration-tests/pom.xml
pom.xml

The new FlusswerkLogger automatically adds tracing paths to all log messages.

Add new FlusswerkLogger

---

framework/pom.xml
integration-tests/pom.xml
pom.xml

Release 4.2.0 brings improved support for structured logging.

Bump version to 4.2.0

---

.github/workflows/ci.yml

See https://github.com/coveooss/fmt-maven-plugin/issues/99

Set CI options for Java 16

---

framework/src/main/java/com/github/dbmdz/flusswerk/framework/engine/Worker.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/flow/Flow.java

Moved duration logging to the right place.

Fix logging

---

framework/pom.xml
framework/src/main/java/com/github/dbmdz/flusswerk/framework/flow/Flow.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/flow/FlowTest.java
integration-tests/pom.xml
pom.xml

Fixes the conversion of duration from nanoseconds to seconds and milliseconds.

Fix duration

---

framework/src/main/java/com/github/dbmdz/flusswerk/framework/reporting/DefaultProcessReport.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/reporting/DefaultProcessReportTest.java

The default process report did add another message field.

Fix message logging

---

framework/src/main/java/com/github/dbmdz/flusswerk/framework/config/FlusswerkConfiguration.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/engine/Worker.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/exceptions/RetryProcessingException.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/flow/Flow.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/rabbitmq/MessageBroker.java
framework/src/main/java/com/github/dbmdz/flusswerk/framework/reporting/Tracing.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/engine/WorkerTest.java
framework/src/test/java/com/github/dbmdz/flusswerk/framework/flow/FlowTest.java

This PR fixes the logic to perform complex retries and simplifies the handling of tracing information. This responsibility is now handled only by `Worker` and is removed from `Flow`.

Fix complex retry
